### ISSUE TITLE
Forced left justification of mapped images - why is this happening?

### ISSUE THREAD

**Issue by jyeager11** [kemayo/maphilight#16]
For the life of me, I can't figure out why this thing justifies my image to the left no matter what I do to break that behavior. I tried applying float:right to it, I tried making sure the container was set to text-align:right... but the darn thing won't budge as long as it has class "map" assigned to it. I even tried applying a style="padding-left:100px" directly on the image to get it away from the left side border, but even that gets ignored.

Soon as I remove the "map" class, however, it behaves normally again. Of course, then it loses its link to this script, so that's no solution.

Anyone know what could be causing this? The behavior is identical on all major browsers and it's really annoying.

**Comment by kemayo** [comment]
The image gets replaced with an arrangement like `<div><canvas></div>`. If the `<img>` has a class, that'll be applied to the div as well, so you can use that to target it instead of specifically targeting the image.

Highly relevant is what gets applied to the `<div>` in the script:

```
wrap = $('<div></div>').css({
				display:'block',
				backgroundImage:'url("'+this.src+'")',
				backgroundSize:'contain',
				position:'relative',
				padding:0,
				width:this.width,
				height:this.height
				});
```

So, you're kind of stuck with `display: block` and `position: relative`.

This, instead of:

img.map {
    margin: 0 auto;
}

do:

.map {
    margin: 0 auto;
}
